### ISSUE TITLE
Cannot start server - "Cannot read property 'join' of undefined"

### ISSUE THREAD

**Issue by rikkiprince** [vincentwoo/setgame#1]
Hi, I'm trying to get this running on a digital ocean instance, to test, but I'm running into the following error. I'm a node.js novice, so apologies if I've done something ridiculous, but I've done a sensible amount of searching and haven't been able to figure out why the path object hasn't been created.

```
DEBUG: Starting child process with 'node server.js'
DEBUG: /root/setgame/node_modules/ams/lib/build.js:130
    targetPath = n.path.join(targetDir, n.path.basename(path));
                       ^

TypeError: Cannot read property 'join' of undefined
    at Build.add (/root/setgame/node_modules/ams/lib/build.js:130:24)
    at buildStaticFiles (/root/setgame/server.js:135:6)
    at Object.<anonymous> (/root/setgame/server.js:17:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

DEBUG: Program node server.js exited with code 1
```

**Comment by vincentwoo** [comment]
Yeah, this old thing is busted. Let me take a crack to see if I can't get it at least barely functional. Sorry bout that.

**Comment by rikkiprince** [comment]
That's fine! Thanks for offering support :-D
